### ISSUE TITLE
mcelog not working on ubuntu kernel

### ISSUE THREAD

**Issue by tlbdk** [andikleen/mcelog#1]
Hi,

I have 3 different machines where I can't get mcelog running, all are running Ubuntu 12.04, I have tried with your git version and get the same result, how would I go about debugging this issue?

tlb@tlbdesk:~/git/webqueue$ cat /proc/cpuinfo|grep 'model name'
model name  : Intel(R) Core(TM)2 Duo CPU     E8500  @ 3.16GHz
tlb@tlbdesk:~/git/webqueue$ sudo mcelog 
mcelog: warning: 16 bytes ignored in each record
mcelog: consider an update

tlb@tlbserv:~$ cat /proc/cpuinfo|grep 'model name'
model name  : Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz
tlb@tlbserv:~$ sudo mcelog 
[sudo] password for tlb: 
mcelog: warning: 16 bytes ignored in each record
mcelog: consider an update

root@web6:/sys/devices/system/machinecheck# cat /proc/cpuinfo|grep 'model name'
model name  : Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
tlb@tlbserv:~$ sudo mcelog 
[sudo] password for tlb: 
mcelog: warning: 16 bytes ignored in each record
mcelog: consider an update

**Comment by paulmenzel** [comment]
As written in the blog post *[mcelog warning bytes ignored consider update](https://blesseddlo.wordpress.com/2010/03/25/mcelog-warning-bytes-ignored-consider-update/)* the reason is a mismatch of the struct `mce` in `/usr/include/asm/mce.h` and `mcelog.h`.

```
$ dpkg -S /usr/include/asm/mce.h
linux-libc-dev: /usr/include/asm/mce.h
$ more /usr/include/asm/mce.h
[…]
/* Fields are zero when not available */
struct mce {
        __u64 status;
        __u64 misc;
        __u64 addr;
        __u64 mcgstatus;
        __u64 ip;
        __u64 tsc;      /* cpu time stamp counter */
        __u64 time;     /* wall time_t when error was detected */
        __u8  cpuvendor;        /* cpu vendor as encoded in system.h */
        __u8  inject_flags;     /* software inject flags */
        __u8  severity;
        __u8  pad;
        __u32 cpuid;    /* CPUID 1 EAX */
        __u8  cs;               /* code segment */
        __u8  bank;     /* machine check bank */
        __u8  cpu;      /* cpu number; obsolete; use extcpu now */
        __u8  finished;   /* entry is valid */
        __u32 extcpu;   /* linux cpu number that detected the error */
        __u32 socketid; /* CPU socket ID */
        __u32 apicid;   /* CPU initial apic ID */
        __u64 mcgcap;   /* MCGCAP MSR: machine check capabilities of CPU */
        __u64 synd;     /* MCA_SYND MSR: only valid on SMCA systems */
        __u64 ipid;     /* MCA_IPID MSR: only valid on SMCA systems */
        __u64 ppin;     /* Protected Processor Inventory Number */
};
[…]
$ git log --oneline -1
9a11988 Merge pull request #41 from splbio/xasprintf
$ more mcelog.h
[…]
/* kernel structure: */

/* Fields are zero when not available */
struct mce {
	__u64 status;
	__u64 misc;
	__u64 addr;
	__u64 mcgstatus;
	__u64 ip;
	__u64 tsc;	/* cpu time stamp counter */
	__u64 time;	/* wall time_t when error was detected */
	__u8  cpuvendor;	/* cpu vendor as encoded in system.h */
	__u8  pad1;
	__u16 pad2;
	__u32 cpuid;	/* CPUID 1 EAX */
	__u8  cs;		/* code segment */
	__u8  bank;	/* machine check bank */
	__u8  cpu;	/* cpu number; obsolete; use extcpu now */
	__u8  finished;   /* entry is valid */
	__u32 extcpu;	/* linux cpu number that detected the error */
	__u32 socketid;	/* CPU socket ID */
	__u32 apicid;	/* CPU initial apic ID */
	__u64 mcgcap;	/* MCGCAP MSR: machine check capabilities of CPU */
};
[…]
```

**Comment by mdunphy** [comment]
Hi,
This problem also appears in Fedora 24 with kernel 4.9.5, with both with the distro-shipped version (mcelog-119-2.fc24.x86_64) and with the latest git version compiled a few minutes ago.

# ./mcelog
mcelog: warning: 16 bytes ignored in each record
mcelog: consider an update

# uname -a
Linux magrathea 4.9.5-100.fc24.x86_64 #1 SMP Fri Jan 20 12:27:44 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

The struct mismatch that Paul mentions is here too, it looks like the kernel people added new fields since the last time struct mce was updated in mcelog..

**Comment by andikleen** [comment]
> The struct mismatch that Paul mentions is here too, it looks like the kernel
> people added new fields since the last time struct mce was updated in mcelog..

Yes a patch is missing. I'm checking with the patch author what
the status is.

-Andi

**Comment by aegl** [comment]
On Sun, Jan 29, 2017 at 3:41 PM, Andi Kleen <notifications@github.com>
wrote:

> > The struct mismatch that Paul mentions is here too, it looks like the
> kernel
> > people added new fields since the last time struct mce was updated in
> mcelog..
>
> Yes a patch is missing. I'm checking with the patch author what
> the status is.
>

Mcelog patch was posted along with the kernel patch back in November:

https://lkml.kernel.org/r/1479429348-1664-1-git-send-email-tony.luck@intel.com

Though:
1) the commit message says kernel versions 4.9 and
    higher ... I think it should say 4.10
2) perhaps the AMD folks that added "synd" and "ipid"
    might want those printed too. But that could be a
    separate patch.

-Tony

>

**Comment by andikleen** [comment]
I added the PPIN patch now, so the message should go away.

Yes SYND and IPID would need to be printed in a separate patch.

**Comment by Nick777818** [comment]
Does anyone know how to disable the mce messages from coming up on boot with Ubuntu 14.04.5 LTS.

root@ld7100e001:~# mcelog --version
mcelog 1.0pre

root@ld7100e001:~# cat /proc/cpuinfo|grep 'model name'
model name	: Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
model name	: Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
model name	: Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
model name	: Intel(R) Celeron(R) CPU J3455 @ 1.50GHz

Un-installing the package does not help either.

mcelog is saying the following:

mcelog: warning: 24 bytes ignored in each record
mcelog: consider an update

Here is the release and Kernel version:

root@ld7100e001:/var/log# lsb_release -a ; uname -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
Linux ld7100e001.ww.lessondesk.com 4.12.0-041200-generic #201707022031 SMP Mon Jul 3 00:32:52 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Any idea on this. Thanks very much!

**Comment by aegl** [comment]
The message is not serious. It just means that you are running on a kernel that added some fields to the “struct mce” and the version of mcelog you have doesn’t know what they are.

If the messages bother you, then build a new mcelog binary from the git sources on kernel.org

-Tony
