### ISSUE TITLE
Small syntax goof in mcelog.logrotate config file [1-2 character quick+easy fix]

### ISSUE THREAD

**Issue by jgottula** [andikleen/mcelog#102]
It seems that `logrotate` (maybe all versions; maybe just recent versions; I dunno, in any case I have `3.18.1`) is a bit grumpy about the `mcelog.logrotate` config file that comes from this repository.
```
Nov 05 00:00:00 helium logrotate[2839170]: mcelog.logrotate:6 keyword 'size' not properly separated, found 0x3d
```

I'll just go ahead and reproduce the entire `mcelog.logrotate` file here for convenience, since (a) it's small and (b) it hasn't been modified a single time over a timespan apparently measured in literal decades. 😝
```
/var/log/mcelog {
    compress
    dateext
    maxage 365
    rotate 99
    size=+2048k
    notifempty
    missingok
    copytruncate
    postrotate
    chmod 644 /var/log/mcelog
    [ -r /var/run/mcelog.pid ] && kill -USR1 `cat /var/run/mcelog.pid`
    endscript
}
```
So, it's this line:
```
    size=+2048k
```
The `0x3d` grievance from `logrotate` is referring to that equals sign `=`. That's not valid syntax. The `size` word and its value should just be separated by a space (similar to the `maxage` and `rotate` lines just above it).

So that sounds like a 1-character fix; pretty easy stuff.

---

Well okay, actually one other very nitpicky little thing to mention is the leading plus `+` character for the value on that same line. I don't think it actually hurts anything, since the way `logrotate` parses size values is to check for a trailing size multiplier suffix (`k`/`M`/`G`), and then shove the rest through `strtoull`; and `strtoull` documents that a leading `+` is valid (and is effectively equivalent to if there was no leading sign character at all).

But, although the `+` being there almost certainly doesn't actually break or affect anything, I think it'd be good to remove it. Mostly it's just a source of potential confusion, because it kinda-sorta implies that it's maybe a *relative* increase over some base/default value or something; when in fact it's merely an absolute size figure that's being extra-explicit about, uh... not being a *negative size*... which is silly in the first place. (And, for what it's worth, I haven't seen an explicit `+` prefix in any of my other package-provided `logrotate` config files.)

So maybe actually just go ahead and do a `s/=\+/ /` on that line (i.e. remove `=+`, replace with ` `).

(I'd make a PR; but for a change this small, it seems maybe a bit silly.)

Thanks!

**Comment by andikleen** [comment]
Thanks!

**Comment by andikleen** [comment]
Well the + is still there now, but I presume it won't hurt anything
