### ISSUE TITLE
"mcelog" command doesn't show machine check log 

### ISSUE THREAD

**Issue by donghuaz** [andikleen/mcelog#116]
See machine check log in message log while it can't be displayed by mcelog tool.
The errors can also be checked by ras-mc-ctl tool.
[root@localhost ~]# dmesg |grep -i machine
...
[202072.518835] mce: [Hardware Error]: Machine check events logged
[202137.695915] mce: [Hardware Error]: Machine check events logged
[202160.831562] mce: [Hardware Error]: Machine check events logged
[root@localhost ~]# ras-mc-ctl --errors
...
112 2023-05-31 10:06:19 -0400 error: MEMORY CONTROLLER RD_CHANNEL0_ERR
Transaction: Memory read error MemCtrl:  Corrected read error bank: 0x1
bankgroup: 0x1 row: 0x3bc90 column: 0x328 failed device: 0xd rank: 0x5
subrank: 0x0 ecc mode:  SDDC, mcg mcgstatus=0, mci Corrected_error,
n_errors=1 memory_channel=0, mcgcap=0x0f000c1c, status=0x8c00004200800090,
addr=0x1efa4c7cc40, misc=0xd03451de4819486, tsc=0x1ddbf37a52d71,
walltime=0x6477545b, cpu=0x00000020, cpuid=0x000606a6, apicid=0x00000080,
socketid=0x00000001, bank=0x0000000d
113 2023-05-31 10:15:13 -0400 error: MEMORY CONTROLLER RD_CHANNEL1_ERR
Transaction: Memory read error MemCtrl:  Corrected read error bank: 0x1
bankgroup: 0x2 row: 0xc1b3 column: 0x338 failed device: 0x5 rank: 0x4
subrank: 0x0 ecc mode:  SDDC, mcg mcgstatus=0, mci Corrected_error,
n_errors=1 memory_channel=1, mcgcap=0x0f000c1c, status=0x8c00004200800091,
addr=0x130ec1dcd80, misc=0xc0146060d999c86, tsc=0x1df016f7edb75,
...
[root@localhost ~]# mcelog
[root@localhost ~]# cat /var/log/mcelog
[root@localhost ~]#
[root@localhost ~]# ps -ef|grep mce
root     1076155       1  0 May30 ?        00:00:00 /usr/sbin/mcelog
--ignorenodev --daemon --logfile=/var/log/mcelog
root     2209157 2208808  0 03:06 pts/0    00:00:00 grep --color=auto mce
[root@localhost ~]#

**Comment by aegl** [comment]
Two possibilities for why you don't see logs.
1) Most modern Linux distributions have switched to systemd. On these systems the logs go to the system journal instead of to /var/log/mcelog. Try # journalctl -a | grep mcelog
2) Your kernel may be configured with CONFIG_RAS_CEC=y. If so, the kernel is just keeping internal statistics for corrected memory errors and not passing them out to mcelog.

**Comment by donghuaz** [comment]
Yes, it works by journalctl now.
[root@localhost ~]# journalctl -a | grep -i mcelog
Jun 13 02:16:39 localhost.localdomain mcelog[5028]: mcelog server already running
Jun 13 02:17:24 localhost.localdomain mcelog[5089]: mcelog server already running
Jun 13 02:17:45 localhost.localdomain systemd[1]: mcelog.service: Succeeded.
Jun 13 02:20:21 localhost.localdomain mcelog[5095]: Hardware event. This is not a software error.
Jun 13 02:20:21 localhost.localdomain mcelog[5095]: MCE 0
Jun 13 02:20:21 localhost.localdomain mcelog[5095]: CPU 32 BANK 14 TSC f9de80e94b
Jun 13 02:20:21 localhost.localdomain mcelog[5095]: MISC c0146060d999c86 ADDR 130ec1dcd80
Jun 13 02:20:21 localhost.localdomain mcelog[5095]: TIME 1686637221 Tue Jun 13 02:20:21 2023
Jun 13 02:20:21 localhost.localdomain mcelog[5095]: MCG status:
Jun 13 02:20:21 localhost.localdomain mcelog[5095]: MCi status:
Jun 13 02:20:21 localhost.localdomain mcelog[5095]: Corrected error
Jun 13 02:20:21 localhost.localdomain mcelog[5095]: MCi_MISC register valid
Jun 13 02:20:21 localhost.localdomain mcelog[5095]: MCi_ADDR register valid
Jun 13 02:20:21 localhost.localdomain mcelog[5095]: MCA: MEMORY CONTROLLER RD_CHANNEL1_ERR
Jun 13 02:20:21 localhost.localdomain mcelog[5095]: Transaction: Memory read error
Jun 13 02:20:21 localhost.localdomain mcelog[5095]: MemCtrl: Corrected read error
Jun 13 02:20:21 localhost.localdomain mcelog[5095]: bank: 0x1 bankgroup: 0x2 row: 0xc1b3 column: 0x338
Jun 13 02:20:21 localhost.localdomain mcelog[5095]: failed device: 0x5
Jun 13 02:20:21 localhost.localdomain mcelog[5095]: rank: 0x4 subrank: 0x0
..
