### ISSUE TITLE
Suspicious places in the application source code

### ISSUE THREAD

**Issue by Yugend** [andikleen/mcelog#118]
I was looking through the source code of mcelog, and found two suspicious places. The first one is in the 'mcelog.c' file, line 782. Due to incorrectly placed brackets, the variable 'n' gets an incorrect value (instead of the sscanf() return value, it gets the result of a comparison sscanf() return values and 1. So 'n' can take only two values: 1 or 0. Because of this, subsequent "if" statements always have a false condition.

Another suspicious place is in the same file, line 667. After checking the condition 'if (n > 2)' the function never checks the condition 'else if (n > 3)'. Maybe instead of 'else if' it would be better to write just 'if'.

Perhaps there is some sense in this, but I did not understand it. In that case, I apologize for the trouble.

-----------------------------------------------------------------
sid@itb.spb.ru | "Innovative Technologies in Business" LLC | https://www.itb.spb.ru/

**Comment by aegl** [comment]
Thanks for the report. Both of the issues you mention are real. I've fixed them and pushed out the updated version.

**Comment by andikleen** [comment]
Thanks for the fixes. Just curious -- how did you find them? Was this reports from some static scanning tool?

**Comment by Yugend** [comment]
Yes, I used the PVS-Studio static analyzer and checked the report I received from the analyzer
