### ISSUE TITLE
Error count

### ISSUE THREAD

**Issue by Alucardfh** [andikleen/mcelog#16]
I am a bit confused with the reporting of mcelog --client.

Either my understanding is wrong or there is something odd with how the total of errors is counted : 

Memory errors
SOCKET 1 CHANNEL any DIMM any
corrected memory errors:
        2654 total
        100 in 24h
uncorrected memory errors:
        0 total
        0 in 24h

SOCKET 1 CHANNEL 3 DIMM any
corrected memory errors:
        1003 total
        10 in 24h
uncorrected memory errors:
        0 total
        0 in 24h

SOCKET 1 CHANNEL 3 DIMM 0
corrected memory errors:
        1651 total
        10 in 24h
uncorrected memory errors:
        0 total
        0 in 24h

Shouldn't the number of corrected errors on SOCKET 1 CHANNEL 3 DIMM any be the same as SOCKET 1 CHANNEL 3 DIMM 0 if only one dimm is failling ?

Can you enlighten me on this as I am afraid I misunderstand the meaning of the output.

**Comment by andikleen** [comment]
any means that mcelog (or rather the hardware) couldn't determine the DIMM number. So it's not necessarily a superset of the individual counts.

**Comment by Alucardfh** [comment]
Hum, that interresting because I checked /var/log/mcelog and it seems to be detecting CPUs and Dimm : 

 cat /var/log/mcelog  | grep BANK | sort | uniq
CPU 10 BANK 12
CPU 10 BANK 7
CPU 11 BANK 12
CPU 11 BANK 7
CPU 12 BANK 12
CPU 12 BANK 7
CPU 13 BANK 12
CPU 13 BANK 7
CPU 14 BANK 12
CPU 14 BANK 7
CPU 15 BANK 12
CPU 15 BANK 7
CPU 16 BANK 12
CPU 16 BANK 7
CPU 17 BANK 12
CPU 17 BANK 7
CPU 18 BANK 12
CPU 18 BANK 7
CPU 19 BANK 12
CPU 19 BANK 7

(Hardware is 2 E5-2680 without hyperthreading so 10 cores each)

From my understanding it is reporting that two dimms have issues on the second CPU but that doesn't match the output of mcelog --client.

Furthermore I believe from the code in dmi.c that mcelog try to detect the dimm using the "Bank Locator" field.

But has you can see below my (dumb ?) vendor only filled the Locator field and not the "BanK Locator"

dmidecode  | grep "Locator"
        Locator: PROC  1 DIMM  1
        Bank Locator: Not Specified
        Locator: PROC  1 DIMM  2
        Bank Locator: Not Specified
        Locator: PROC  1 DIMM  3
        Bank Locator: Not Specified
        Locator: PROC  1 DIMM  4
        Bank Locator: Not Specified
        Locator: PROC  1 DIMM  5
        Bank Locator: Not Specified
        Locator: PROC  1 DIMM  6
        Bank Locator: Not Specified
        Locator: PROC  1 DIMM  7
        Bank Locator: Not Specified
        Locator: PROC  1 DIMM  8
        Bank Locator: Not Specified
        Locator: PROC  2 DIMM  1
        Bank Locator: Not Specified
        Locator: PROC  2 DIMM  2
        Bank Locator: Not Specified
        Locator: PROC  2 DIMM  3
        Bank Locator: Not Specified
        Locator: PROC  2 DIMM  4
        Bank Locator: Not Specified
        Locator: PROC  2 DIMM  5
        Bank Locator: Not Specified
        Locator: PROC  2 DIMM  6
        Bank Locator: Not Specified
        Locator: PROC  2 DIMM  7
        Bank Locator: Not Specified
        Locator: PROC  2 DIMM  8
        Bank Locator: Not Specified


Would it be a good idea to also parse the Locator field ?
The only thing I see is that it doesn't report the channel on which the dimm belongs to but my understanding might not be perfect.

**Comment by andikleen** [comment]
The dmi code is not really used (should probably remove it). Modern memory controllers are far too complicated for such a simple table. It uses the DIMM number reported by the hardware.  Sometimes it reports "don't know"

Yes I guess should handle Locator too. Reopening to handle that.

**Comment by Alucardfh** [comment]
Hi,

I still find that the count display in  Channel any dimm any is not quite right : 

In the example below the count in SOCKET 1 CHANNEL any DIMM any is the sum of all events on any channels on socket 1. But it doesn't take into account the number of event in the last 24H.

81997364  = 154  + 50  + 30307676  + 8951  + 51680318  + 215 

Sorry about the big number ... this server has indeed issues with its memory.

By the way could you explain how mcelog picks up the channel and dimm from the errors thrown by the CPU ?

Memory errors
SOCKET 1 CHANNEL any DIMM any
corrected memory errors:
        81997364 total
        0 in 24h
uncorrected memory errors:
        0 total
        0 in 24h

SOCKET 1 CHANNEL 0 DIMM any
corrected memory errors:
        154 total
        133 in 24h
uncorrected memory errors:
        0 total
        0 in 24h

SOCKET 1 CHANNEL 1 DIMM any
corrected memory errors:
        50 total
        5 in 24h
uncorrected memory errors:
        0 total
        0 in 24h

SOCKET 1 CHANNEL 2 DIMM any
corrected memory errors:
        30307676 total
        810913 in 24h
uncorrected memory errors:
        0 total
        0 in 24h

SOCKET 1 CHANNEL 2 DIMM 0
corrected memory errors:
        8951 total
        15 in 24h
uncorrected memory errors:
        0 total
        0 in 24h

SOCKET 1 CHANNEL 2 DIMM 1
corrected memory errors:
        51680318 total
        445171 in 24h
uncorrected memory errors:
        0 total
        0 in 24h

SOCKET 1 CHANNEL 3 DIMM any
corrected memory errors:
        215 total
        3 in 24h
uncorrected memory errors:
        0 total
        0 in 24h

**Comment by andikleen** [comment]
>By the way could you explain how mcelog picks up the channel and dimm from the errors thrown by the CPU ?
The channel comes from the machine check code (it's in the code, see the ascii decoding). The DIMM depends on the CPU, but it's normally some magic encoding in MISC

**Comment by andikleen** [comment]
the original reporting problem should be fixed now with.
We didn't age the counters on reporting.

commit 864571586a7d7430a59d7fba1c979e1fb8ee88ce
Author: Rui Wang <rui.y.wang@intel.com>
Date:   Tue Mar 31 15:43:46 2015 +0800

    Fix error count during the last agetime
