### ISSUE TITLE
Suppress specific messages

### ISSUE THREAD

**Issue by comfine** [andikleen/mcelog#18]
would be great to be able to suppress specific messages!
reason:  mcelog send's me this "randomly":

mcelog: Unsupported new Family 6 Model 3c CPU: only decoding architectural errors

if i understand that right, this is nothing really bad, or? so...of course i want to be informed if something is going wrong with the hardware, but i don't want to get this message every day.... using an email-filter is not a very nice solution..also, i'm not a linux-crack and don't know how i can suppress this via some "filter-script" in cron....
i think, it would be nice if users can put some exceptions in the config-file for messages, they dont want to get send out via mail? 
what do you think?

**Comment by andikleen** [comment]
mcelog never sends email directly. The script that does it would need to filter that. The message happens once every time mcelog starts.

BTW I don't recommend configuring mcelog to send email. If your machine dies you may get a lot of email. It's always better to summarize errors and only take actions on triggers.
