### ISSUE TITLE
 only decoding architectural errors

### ISSUE THREAD

**Issue by uabmagj** [andikleen/mcelog#20]
localhost user.err mcelog: Family 6 Model 4d CPU: only decoding architectural errors
localhost user.err mcelog: Kernel does not support page offline interfacealsh.. 

We get these errors during Linux boot, What we are wondering about is if its only the decoding of the errors that are missing or if the actual errors reported by cpu is missing...

**Comment by andikleen** [comment]
Only the decoding is missing. All errors are still logged.
