### ISSUE TITLE
AMD CPU Family 15 read error

### ISSUE THREAD

**Issue by tszr** [andikleen/mcelog#21]
mcelog uses /proc/cpuinfo to read cpu family information. However, it reads 21 (dec) for cpu family 15 (hex) and aborts operation saying doesn't support anything other than 15. It needs to be fixed. I have access to 6 AMD machines and mcelog is running on none because of this.

**Comment by andikleen** [comment]
15 is always decimal and mcelog reads it correctly. mcelog doesn't support newer AMD CPUs anymore, as AMD decided to not support it anymore due to some confusion on their part.

**Comment by tszr** [comment]
All my systems are CPU Family 15, that I am certain about. I am internal to AMD. Also if I do cpuid, that gives 15 but /proc/cpuinfo gives 21. 
I also wrote my own scripts to verify that.

**Comment by andikleen** [comment]
Ok.  I think the model handling is still correct, there is simply no support for family 21.

Some previous AMD RAS person decided to only support EDAC. The AMD kernel machine check code doesn't report its errors through /dev/mcelog. If that was fixed in the kernel it would be possible to update mcelog to handle the errors again. Some custom code may need be written to handle the difference since K8, decode newer machine check, and enable DIMM decoding/accounting.

**Comment by tszr** [comment]
Yes, I am aware of it. We plan to work on it further so that mcelog supports newer generation.
However, current mcelog supports family 15, at least that should work.
Basically let me clearly explain what I am talking about. I apologize I wasn't clear enough earlier.
I have 6 AMD systems, all family 15. If I run cpuinfo or cpuid, it dumps family as 15. But if I do /proc/cpuinfo, it dumps 21. Then I wrote 2 scripts, one in C and one in C++, both read /proc/cpuinfo and dumps the family number. The C version dumps 21 and C++ dumps 15. I didn't dig into it much why it is doing so. Then I went into mcelog code and modified it to dump the family in dec and hex.  So basically mcelog is reading decimal 21 but comparing it with 15 and aborting. 
does it make sense?

**Comment by andikleen** [comment]
Thanks.

decimal 15 aka 0xF was Barcelona. Is that what you have? That was the last AMD CPU supported. I assume decimal 21 is something much newer.

**Comment by tszr** [comment]
As far as I know 0xF are trinity/orochi/bulldozer based ones. Barcelona is 10 (http://en.wikipedia.org/wiki/AMD_10h). 
So you think mcelog supports only barcelona?

**Comment by andikleen** [comment]
Yes sorry 0xf was K8, 0x10 barcelona. I think we actually stopped at K8, not Barcelona.
That is before 
https://github.com/andikleen/mcelog/commit/cd9e67dc17bf463d09a67feb76a55852eaf6ee1d
went in Barcelona should have worked with the K8 code (as it matched all larger families), but only on older kernels that didn't have the EDAC eats everything problem.

**Comment by tszr** [comment]
Yes. I have the K8 ones. Do you think the /proc/cpuinfo read can be adjusted?

**Comment by andikleen** [comment]
You mean adjusting it to detect newer CPU families? Yes of course, but only if it actually works:
- the kernel outputs the right information
- mcelog gains the necessary code to decode any newer machine check codes beyond k8
(at least the ones that matter to users)
- some dimm decoding support would be also good
Feel free to propose patches.

**Comment by tszr** [comment]
I am having trouble with the K8 ones. I am attaching two figures which might be helpful to express the problem.
![cpuid](https://cloud.githubusercontent.com/assets/11447478/6675205/35383902-cbdc-11e4-9f0b-7372ee4d22f8.JPG)
![mcelog](https://cloud.githubusercontent.com/assets/11447478/6675212/39c6d3fc-cbdc-11e4-84ee-e4f04a20e950.JPG)

**Comment by tszr** [comment]
![mcelog code](https://cloud.githubusercontent.com/assets/11447478/6675251/6b9026cc-cbdc-11e4-9f96-f379dbb80e1a.JPG)

**Comment by tszr** [comment]
Hi Andi, as you can see mcelog is outputting error saying family 21 whereas it is family 15. It is just reading the decimal version, not 15h. Can we fix this for the existing systems? Then I will work on the newer generation support.

**Comment by andikleen** [comment]
So the kernel does:
                   "cpu family\t: %d\n"
mcelog does:
     if (sscanf(line, "cpu family : %d", &family) == 1)
                                seen |= FAMILY;

So it's all decimal. I don't see where it could mis-parse. 

What does grep family /proc/cpuinfo say on your K8 system?

**Comment by andikleen** [comment]
So I checked your screen shot

CPUID 1 EAX = 0x610f01
The family is [8...11] and extended family [20..27].

Doesn't look like a K8 to me. K8 was family 15 (0xf), so the extended family should be all 0.

**Comment by tszr** [comment]
Yes Family is [8..11] and extended family is [20..27]. The way you calculated the final family is:
The Family is an 8-bit value and is defined as: Family[7:0] = ({0000b,BaseFamily[3:0]} + ExtendedFamily[7:0]). (http://support.amd.com/TechDocs/25481.pdf)
So in my case, base family: 0xF and extended family 0x6. using the above formula it is 0xF.

**Comment by tszr** [comment]
I think there is nothing wrong with the parsing, it is just reading decimal 21 which is  correct. We just need to compare it with decimal 21 instead of 15h or convert the decimal 21 to hex and compare with 15h.

**Comment by andikleen** [comment]
But I'm pretty sure the original K8 had family 0xf.

The kernel code in amd.c agrees with that too, e.g. in amd.c:

        WARN_ONCE((boot_cpu_data.x86 != 0xf),
                  "%s should only be used on K8!\n", __func__);

So your family 21 is not a K8 but something else. So there's no indication that there's a problem with the K8 code.

I'm fine with adding support for family 21 (and other families), but unless it's 100% compatible to K8 for machine checks other code than just the model detection would need to be changed. Let's handle that separately, e.g. with a pull request.

**Comment by tszr** [comment]
All I am talking about is the following change, if I do this, mcelog runs in my systems which is K8:
![mcelog_comparison](https://cloud.githubusercontent.com/assets/11447478/6698578/0029d29e-ccb7-11e4-8caa-abef47070437.JPG)

Thanks much for your patience!

**Comment by andikleen** [comment]
I'm pretty sure the change is not correct, as K8 is family 0xf

If your family 0x15 really was 100% compatible to K8 for MCEs the code could be:

if (family == 15 || family == 0x15) { 
           cputype = CPU_K8;
}

I don't know if that's the case or not.

**Comment by tszr** [comment]
Hey Andi, sorry about the confusion. I got confused with all the decimal and hex numbers. There are 0xF, 0x15, and 0x21. Basically you are saying mcelog stopped at 0xF and we are looking at the newer generation once. I will get back to you once we sort out all the MCA logging differences. Thanks!
