### ISSUE TITLE
mcelog is not logging mem & page errors

### ISSUE THREAD

**Issue by vpedabal** [andikleen/mcelog#23]
Hi,
I tested injecting errors using the scripts in the test folder. The cache error injection seems to trigger logging in syslog, however the memdb and page error-injections seems to be getting ignored by mcelog. They do get reported by the kernel and EDAC. Are there any any specifc knobs I need to enable for turning on this feature?

P.S. Is there a mailing list for posting questions? Or the github issues the right place to ask? Thanks.

**Comment by andikleen** [comment]
Apparenty was due to EDAC. Added to FAQ.
