### ISSUE TITLE
Review Debian patches

### ISSUE THREAD

**Issue by wRAR** [andikleen/mcelog#24]
Hello. The Debian mcelog package has quite a lot of patches, all of them seem useful to all users. Please review them and apply ones that are useful.

http://anonscm.debian.org/cgit/collab-maint/mcelog.git/tree/debian/patches

**Comment by andikleen** [comment]
Can you please submit them as patches in email?

Thanks.

**Comment by wRAR** [comment]
`git format-patch` or just as attachments to a single email?

**Comment by andikleen** [comment]
On Tue, Jul 21, 2015 at 09:27:32AM -0700, Andrey Rahmatullin wrote:
> `git format-patch` or just as attachments to a single email?

format-patch.

-Andi

**Comment by andikleen** [comment]
Did you send the emails? I don't see them

**Comment by wRAR** [comment]
Sorry for the delay, I've sent them now

**Comment by andikleen** [comment]
Merged
