### ISSUE TITLE
retrieve hardware failure information from the mcelog socket

### ISSUE THREAD

**Issue by meow-watermelon** [andikleen/mcelog#30]
Hi,

I'm writing a small program to detect hardware failure and would like to use mcelog socket to retrieve error messages. However, it seems the socket just returns "done" but nothing else.

```
[server] 
# socat -d -d TCP-LISTEN:8080,fork UNIX:/var/run/mcelog-client 

[client] 
# echo "pages" | nc localhost 8080
done
# echo "dump bios all" | nc localhost 8080
done
```

So basically I expect to see some output like http://mcelog.org/protocol.html mentions. Is that normal behavior? If yes, is there any way that we can retrieve hardware failures from mcelog?

Thanks.

**Comment by andikleen** [comment]
Do you actually have any errors?

Pass the all flag to see units with no errors
Try injecting some errors (see the test suite)

**Comment by meow-watermelon** [comment]
Hi,

Thanks for your reply. However, even I triggered the test suite seems I still got nothing from the socket.

`
[server]
# socat -d -d TCP-LISTEN:8080,fork UNIX:/var/run/mcelog-client

[test steps]
# modprobe mce_inject
# lsmod | grep mce_inject
mce_inject             16384  0
# cd ~/mcelog/tests
# ./test page
++++++++++++ running page test +++++++++++++++++++
mcelog: no process found
# echo $?
0

[client]
>>> I run the following command while the test is running
# echo "pages" | nc localhost 8080
#
>>> Got nothing. The socat reported following errors:
2016/01/08 00:29:43 socat[5836] N accepting connection from AF=2 127.0.0.1:54330 on AF=2 127.0.0.1:8080
2016/01/08 00:29:43 socat[5836] N forked off child process 6001
2016/01/08 00:29:43 socat[5836] N listening on AF=2 0.0.0.0:8080
2016/01/08 00:29:43 socat[6001] N opening connection to AF=1 "/var/run/mcelog-client"
2016/01/08 00:29:43 socat[6001] E connect(3, AF=1 "/var/run/mcelog-client", 24): Connection refused
2016/01/08 00:29:43 socat[6001] N exit(1)
2016/01/08 00:29:43 socat[5836] W waitpid(): child 6001 exited with status 1
>>> However, the results are generated properly:
# ls -ltr page/
total 108
-rw-r--r--. 1 root root   213 Jan  6 23:53 page-soft-then-hard.conf
-rw-r--r--. 1 root root   203 Jan  6 23:53 page-soft.conf
-rw-r--r--. 1 root root   202 Jan  6 23:53 page-off.conf
-rw-r--r--. 1 root root   383 Jan  6 23:53 page-memdb.conf
-rw-r--r--. 1 root root   203 Jan  6 23:53 page-hard.conf
-rw-r--r--. 1 root root   206 Jan  6 23:53 page-account.conf
-rwxr-xr-x. 1 root root   274 Jan  6 23:53 inject
-rw-r--r--. 1 root root  2403 Jan  8 00:29 page-account.log
-rw-r--r--. 1 root root  2425 Jan  8 00:29 page-hard.log
-rw-r--r--. 1 root root  4150 Jan  8 00:29 page-memdb.log
-rw-r--r--. 1 root root  2373 Jan  8 00:29 page-off.log
-rw-r--r--. 1 root root  2476 Jan  8 00:29 page-soft.log
-rw-r--r--. 1 root root  2578 Jan  8 00:29 page-soft-then-hard.log
-rw-r--r--. 1 root root 43142 Jan  8 00:29 result
-rw-r--r--. 1 root root   283 Jan  8 00:29 results
`

Could you pls. let me know which step could be wrong?

Thanks.

Hui

**Comment by andikleen** [comment]
The test suite kills mcelog so there is no history over it. You have to inject your own errors.

**Comment by meow-watermelon** [comment]
Hi,

I just tried one problematic host w/ memory error and it works:

```
Memory errors
SOCKET 1 CHANNEL any DIMM any
corrected memory errors:
	4144 total
	0 in 24h
uncorrected memory errors:
	0 total
	0 in 24h

SOCKET 1 CHANNEL 2 DIMM 0
corrected memory errors:
	3171 total
	3171 in 24h
uncorrected memory errors:
	0 total
	0 in 24h
done
```

Thanks.
