### ISSUE TITLE
mcelog does not start on Haswell-EP (bisected)

### ISSUE THREAD

**Issue by N0T3P4D** [andikleen/mcelog#32]
Running strace mcelog --daemon fails with the following error:

[...]
connect(6, {sa_family=AF_LOCAL, sun_path="/dev/log"}, 110) = -1 ENOENT (No such file or directory)
close(6)                                = 0
fstat(3, {st_mode=S_IFREG|0644, st_size=3997, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f040abc1000
open("/sys/devices/system/cpu", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 6
fstat(6, {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
getdents(6, /* 22 entries */, 32768)    = 624
getdents(6, /* 0 entries */, 32768)     = 0
close(6)                                = 0
open("/dev/cpu/0/msr", O_RDWR)          = 6
pread64(6, 0x7ffe6c0b8320, 8, 383)      = -1 EIO (Input/output error)
socket(PF_LOCAL, SOCK_DGRAM|SOCK_CLOEXEC, 0) = 7
connect(7, {sa_family=AF_LOCAL, sun_path="/dev/log"}, 110) = -1 ENOENT (No such file or directory)
close(7)                                = 0
write(3, "Kernel does not support page off"..., 126) = 126
exit_group(1)                           = ?
+++ exited with 1 +++

I've bisected the problem. The offending commit is 0bcf16fd3566eb99a6fbbaf29c69cc4de7d30ade which seems to match my hardware:

Xeon E5-1620 v3
Supermicro X10SRL-F, BIOS v2.0
The kernel version is 4.3.5.

**Comment by andikleen** [comment]
The commit should fix your problem, but the DIMM logging will still not work.
We tested the MSR write and it works on our system.

Possible things that could break it:
- You run in some kind of VM that rejects the MSR write
- You have some security module running that prevents MSR writes
- You have some kernel patch that prevents MSR writes in a secure kernel.

**Comment by N0T3P4D** [comment]
Thanks for your quick response! I can confirm that mcelog now starts successfully. In particular, I want to use it to watch for (un)corrected RAM errors, so I guess I'll have to keep investigating.
As for the MSR write: I run Gentoo with a custom-compiled kernel straight from linux-stable git and I'm not aware of any of the points you mention. The only esoteric thing about my setup is that I have Intel TXT enabled in the BIOS, but the kernel was loaded normally (without tboot).

I'll try disabling TXT, see if I can reproduce the problem with a different distribution / kernel and get back to you.

**Comment by andikleen** [comment]
No need to try a different distribution.

Can you read any msrs?

Install msr-tools and run rdmsr -a 1

**Comment by andikleen** [comment]
Actually better to try to write them.

wrmsr -a 0xc2 1000

Disabling TXT is also useful to try.

**Comment by N0T3P4D** [comment]
notepad msr-tools # ./wrmsr -a 0xc2 1000

notepad msr-tools # ./rdmsr -a 1

0
0
0
0
0
0
0
0
notepad msr-tools # ./rdmsr -a 0xc2

3e8
3e8
3e8
3e8
3e8
3e8
3e8
3e8

This is with TXT still enabled.  
The "Kernel does not support page off"... seems to be due to some missing kernel option. On Fedora 23 and Ubuntu 14.04, using mcelog from git with rev f3831561806044c8dd7665e531d7e36972ee10f7, it fails with the following message:
write(3, "mcelog: Cannot read MSR_ERROR_CO"..., 79) = 79

**Comment by andikleen** [comment]
So it looks like basic MSR writes work.

What do you see for wrmsr -a 0x17f 2 ?

**Comment by N0T3P4D** [comment]
notepad msr-tools # ./wrmsr -a 0x17f 2 
notepad msr-tools # ./rdmsr -a 0x17f
rdmsr: CPU 0 cannot read MSR 0x0000017f

strace looks like this:

[...]
open("/dev/cpu", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFDIR|0755, st_size=220, ...}) = 0
brk(NULL)                               = 0xec7000
brk(0xef0000)                           = 0xef0000
getdents(3, /* 11 entries */, 32768)    = 272
getdents(3, /* 0 entries */, 32768)     = 0
close(3)                                = 0
open("/dev/cpu/0/msr", O_WRONLY)        = 3
pwrite64(3, "\2\0\0\0\0\0\0\0", 8, 383) = 8
close(3)                                = 0
[...]

**Comment by andikleen** [comment]
Ok so the write works, but the read doesn't. That's very odd.

**Comment by N0T3P4D** [comment]
Should I complain to Supermicro or anyone else?

**Comment by N0T3P4D** [comment]
I've reproduced the error with TXT disabled.

**Comment by aegl** [comment]
Can you give some more information from /proc/cpuinfo? Mostly the stepping and microcode rev, or just paste in the whole entry for the first logical cpu.

**Comment by N0T3P4D** [comment]
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 63
model name      : Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz
stepping        : 2
microcode       : 0x36
cpu MHz         : 1199.980
cache size      : 10240 KB
physical id     : 0
siblings        : 8
core id         : 0
cpu cores       : 4
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 15
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm xsaveopt cqm_llc cqm_occup_llc
bugs            :
bogomips        : 7000.37
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

**Comment by andikleen** [comment]
Could you please also send the output of rdmsr -a 0x179 ?

**Comment by N0T3P4D** [comment]
notepad msr-tools # ./rdmsr -a 0x179
7000c16
7000c16
7000c16
7000c16
7000c16
7000c16
7000c16
7000c16

**Comment by carlsonj** [comment]
Same here on an E5-1650.  I was able to get the daemon to run by doing the following:

/usr/sbin/mcelog --cpu haswell --daemon

... but I'm guessing that disabling the "EP" parts of the daemon makes the ECC error detection ineffective.

**Comment by andikleen** [comment]
Disabling EP only disables the detection of the DIMM that had the problem.

You got a SuperMicro system too?

It should work with commit 89d3888aa applied.

We verified that the BIOS can put the CPU into a mode where the reading of this MSR fails. But it should not affect the other mcelog operation, so it can be ignored.

**Comment by carlsonj** [comment]
No, it's an ASRock X99-WS motherboard.  I can probably wait for that fix to show up in OpenSuSE Tumbleweed; thanks.

**Comment by AdamWill** [comment]
For the record, we're seeing something along these lines in Fedora, on our openQA deployment. One of our openQA 'worker host' boxes (that run the VMs that run the actual tests) has a Xeon E5-2450 CPU. When openQA starts a VM on that box and boots Fedora, mcelog fails to start, with the `Cannot read MSR_ERROR_CONTROL from /dev/cpu/0/msr` error. https://bugzilla.redhat.com/show_bug.cgi?id=1337582 is our bug report for this. I think it only happens in VMs; I just installed mcelog directly on the box and started it and it started up OK.

I'll add this patch to the Fedora mcelog package, hopefully it'll make the problem go away...
