### ISSUE TITLE
mcelog hangs in the non-dameon mode when unknown error is encountered 

### ISSUE THREAD

**Issue by srilakshmidj** [andikleen/mcelog#33]
In the non-daemon mode, when the child processes exit the SIGCHLD
is being read off the queue, but the child handler is not called,
and the num_children is not decremented. This leads to the process
hanging in trigger_wait() function in an infinite loop waiting for
SIGCHLD signals that never arrive - (sigwait(&mask, &sig)).

This behaviour was discovered when the mcelog tried to process an
unknown error on a machine, and created child processes. The parent
process never exited. Since mcelog was run by a cron task every x
minutes, numerous hung-mcelog processes accumulated whenever it hit
the unknown-error-trigger.

Sample error lines:
mcelog: Running trigger unknown-error-trigger' mcelog: Running triggerunknown-error-trigger'
mcelog: CPU 5 on socket 0 received unknown error
mcelog: CPU 5 on socket 0 received unknown error

The fix is to call waitpid() to reap the exit status of all terminating
children, calling finish_child() for each. This fix has been tested
on the machine the issue was discovered on.

srilakshmidj-patch-1 on branch  srilakshmidj/mcelog fixes the problem.

Signed-off-by: Tim Bingham tbingham@akamai.com
Signed-off-by: Sri Jayaramappa sjayaram@akamai.com

**Comment by andikleen** [comment]
Thanks for the analysis. Please send a pull request with the patch.

BTW I would really recommend to use daemon mode. This allows bad page offlining and other predictive features, which can avoid problems at runtime.

**Comment by srilakshmidj** [comment]
Just did, thanks.
