### ISSUE TITLE
mcelog throws  "only decoding architectural errors" on skylake processors

### ISSUE THREAD

**Issue by saurabh-hp** [andikleen/mcelog#35]
mcelogs need support for new Intel skylake processors. Below errors is seen in /var/log/mcelog.

mcelog: mcelog read: No such device
mcelog: Family 6 Model 55 CPU: only decoding architectural errors
Hardware event. This is not a software error.
MCE 0
CPU 0 BANK 11 
MISC 229aa040900086 ADDR fffc4b00 
TIME 1458750006 Wed Mar 23 12:20:06 2016
MCG status:
MCi status:
Uncorrected error
MCi_MISC register valid
MCi_ADDR register valid
Processor context corrupt
MCA: corrected filtering (some unreported errors in same region)
Generic CACHE Level-2 Generic Error
STATUS ae2000000003110a MCGSTATUS 0
MCGCAP 6000c14 APICID 0 SOCKETID 0 
CPUID Vendor Intel Family 6 Model 85

**Comment by andikleen** [comment]
Support will be added as soon as the documentation for this is released

**Comment by andikleen** [comment]
Fixed with e4aca6312aee
