### ISSUE TITLE
Please add domains {,www.}mcelog.org to certificate

### ISSUE THREAD

**Issue by paulmenzel** [andikleen/mcelog#43]
Currently, the browser shows the warning below.

> www.mcelog.org uses an invalid security certificate.
>
> The certificate is only valid for the following names:
>   firstfloor.org, www.firstfloor.org
>
> Error code: SSL_ERROR_BAD_CERT_DOMAIN

It’d be great if the domains could be added to the certificate.

**Comment by andikleen** [comment]
mcelog.org has its own certificate now
