### ISSUE TITLE
[Web site] Improve SSL configuration

### ISSUE THREAD

**Issue by paulmenzel** [andikleen/mcelog#45]
It’d be great if the SSL configuration of the Web server could be improved.

```
$ curl -I https://www.mcelog.org
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html
[…]
$ openssl s_client -showcerts -verify_hostname www.mcelog.org -connect www.mcelog.org:443
[…]
```

The [Qualys SSL Report for the domain](https://www.ssllabs.com/ssltest/analyze.html?d=www.mcelog.org) grades an F.

So I’d be great, if the Web server sent the intermediate certificate.

> Let's Encrypt Authority X3
> Fingerprint SHA1: e6a3b45b062d509b3382282d196efe97d5956ccb
> Pin SHA256: YLh1dUR9y6Kja30RrAn7JKnbQG/uEtLMkBgFF2Fuihg=
> RSA 2048 bits (e 65537) / SHA256withRSA

The Web site [Cipherli.st](https://cipherli.st/) also contains SSL configuration snippets for popular HTTPD servers.

**Comment by paulmenzel** [comment]
Running the check again, a lot has improved. Thank you. There are still some small issues left.

* This server accepts RC4 cipher, but only with older protocols. Grade capped to B.
* The server does not support Forward Secrecy with the reference browsers.
* This server's certificate chain is incomplete. Grade capped to B.

**Comment by andikleen** [comment]
If you don't like the website don't use it.
