### ISSUE TITLE
build failure with dash shell

### ISSUE THREAD

**Issue by benkohler** [andikleen/mcelog#48]
When /bin/sh is pointing to dash or some other non-bash shells, the Makefile code generating version.c fails.  The "echo -n" literally prints an unwanted "-n" into the file. This results in the build failure below:

x86_64-pc-linux-gnu-gcc -c -O2 -pipe -march=native  -Wall -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -Wstrict-prototypes -Wformat-security -Wmissing-declarations -Wdeclaration-after-statement  -o version.o version.c
version.c:1:1: error: expected identifier or ‘(’ before ‘-’ token
 -n char version[] = "
 ^
version.c:1:21: warning: missing terminating " character
 -n char version[] = "
                     ^
version.c:1:1: error: missing terminating " character
 -n char version[] = "
 ^
version.c:3:1: warning: missing terminating " character
 ";
 ^
version.c:3:1: error: missing terminating " character
make: *** [Makefile:88: version.o] Error 1

**Comment by benkohler** [comment]
This is the contents of version.c:

-n char version[] = "
-n unknown
";

**Comment by paulmenzel** [comment]
Is that a regression of pull request #47 trying to fix issue #42? Or did that never work?

**Comment by andikleen** [comment]
There's no echo -n in the git version. Please update.
