### ISSUE TITLE
mcelog client fails with "permission denied"

### ISSUE THREAD

**Issue by kovyrin** [andikleen/mcelog#53]
There is an issue on systems with linux systems running kernel XXX or higher (any kernels where https://android.googlesource.com/kernel/common.git/+/16e5726269611b71c930054ffe9b858c1cea88eb has been applied). Mcelog client randomly fails with a "permission denied" error. 

Here is how it happens:
1) mcelog daemon creates a unix streaming socket with `listen()`
2) mcelog client connects to it
3) mcelog daemon calls `accept()`
4) mcelog daemon calls `setsockopt(SO_PASSCRED)` and asks the kernel to pass uid/gid of the client
5) mcelog client sends its commands
6) mcelog daemon receives commands, checks uid to be 0, responds, all good

It is all good when it works, but there is a race between steps 4 and 5. If the client is too fast, the message arrives without credentials and kernel just sets uid=nobody. Mcelog daemon checks that and denies the request.

After the initial commit to linux, there has been a fix in 90c6bd34f884cd9cee21f1d152baf6c18bcac949 (described here: https://lists.ubuntu.com/archives/kernel-team/2013-October/033188.html), that, if mcelog code is changed to set `SO_PASSCRED` on the listen socket, would fix the race.

**Comment by andikleen** [comment]
Thanks for the detailed report.

I think I cannot just move it because that would break old kernels that don't support SO_PASSCRED Inheritance. So I just do it on both (but don't check the error in the listen case)

**Comment by kovyrin** [comment]
Yeah, doing it on both sockets would do the trick AFAIU.

**Comment by andikleen** [comment]
Fixed in def5f22ab7f2134a7bdd82f70ff0c1ef16fe3731

Some more testing would be appreciated.
