### ISSUE TITLE
mcelog: ERROR: AMD Processor family 22: mcelog does not support this processor. 

### ISSUE THREAD

**Issue by whtcr** [andikleen/mcelog#62]
Hello dear Developer!

I have a CPU: Quad Core AMD A8-6410 APU with AMD Radeon R5 Graphics (-MCP-)

For every linux distribution I get this error:
mcelog: ERROR: AMD Processor family 22: mcelog does not support this processor.  Please use the edac_mce_amd modul

Please fix this bug.

Thank you very much!
László Kardos # #

**Comment by devurandom** [comment]
The [FAQ](http://www.mcelog.org/faq.html#18) should answer your question:

>  AMD stopped supporting mcelog. If you want to use it please contact AMD. Update: support is being worked on now.

**Comment by commandline-be** [comment]
Any news yet ? Just installed the most recent version of mcelog, cpu not supported. AMD Ryzen 1st gen.

**Comment by andikleen** [comment]
On Sun, Jun 21, 2020 at 12:06:55AM -0700, commandline_be wrote:
> Any news yet ? Just installed the most recent version of mcelog, cpu not
> supported. AMD Ryzen 1st gen.

Someone would need to support a patch to support it. Maybe check with
AMD. They indicated some time ago they were interested, but never saw
any patches submitted.

-Andi

**Comment by DOGSHITD** [comment]
Hi Sir,

We making full use of convenience brought by mcelog at our production line, we would not like to change from mcelog to edac for AMD newer platform, because we have customized code in mcelog driver. May I know the latest status from AMD? or how we can reach it out to AMD? Much appreciated!

Thanks,
Boyce
