### ISSUE TITLE
For uncorrected errors, how do we determine which memory address the error has occurred?

### ISSUE THREAD

**Issue by meeraramesh** [andikleen/mcelog#63]
For ex: Consider the log for uncorrected error:
Hardware event. This is not a software error.
MCE 0
CPU 0 BANK 2 TSC 41cc435c49086
MISC 40000
TIME 1462844438 Tue May 10 01:40:38 2016
MCG status:
MCi status:
Uncorrected error
Error enabled

Consider the log for corrected error:
Hardware event. This is not a software error.
MCE 0
CPU 0 BANK 2
MISC 50000 ADDR 389f000
TIME 1462783860 Mon May  9 08:51:00 2016
MCG status:
MCi status:
Corrected error

Why isn't "ADDR 389f000" not present for uncorrected errors and how do we determine it?

**Comment by andikleen** [comment]
mcelog just reports what the CPU reports. If it's not included there is no way to determine it.
