### ISSUE TITLE
Segmentation fault of the mcelog daemon on Broadwell E5-2660V4

### ISSUE THREAD

**Issue by ifke** [andikleen/mcelog#65]
The mcelog daemon crashes because of segmentation fault on our Broadwell E5-2660V4 processors. We see the following kernel message on hosts with ECC memory errors:
```
Mar 13 15:17:17 server kernel: [22312023.287737] mcelog[473830]: segfault at 80 ip 000000000040aac8 sp 00007fffa4bec658 error 4 in mcelog[400000+15000]
Mar 14 10:23:54 server kernel: [22380816.522131] mcelog[169928]: segfault at 70 ip 000000000040aac8 sp 00007ffc191d87e8 error 4 in mcelog[400000+15000]
```
We use version 153, but the problem is reproduced on the last version 156 as well. The kernel version is 4.4.88-42.

To simplify analysis we compiled the binary mcelog.debug with -g3 -O0 options and get the core dump. The both files are here [mcelog-crash.zip](https://github.com/andikleen/mcelog/files/1811104/mcelog-crash.zip).

**Comment by andikleen** [comment]
Thanks. Looks like I broke this in c18c8048f226244, quite some time ago.
The color field was shrunk to a char, but it still contains a pointer.
Just turn it back into an unsigned long
