### ISSUE TITLE
mcelog read: No such device

### ISSUE THREAD

**Issue by ugiwgh** [andikleen/mcelog#73]
mcelog: failed to prefill DIMM database from DMI data
mcelog: mcelog read: No such device
Hardware event. This is not a software error.
MCE 0
CPU 9 BANK 5 
MISC 100 
TIME 1549963550 Tue Feb 12 17:25:50 2019
MCG status:
MCi status:
Error overflow
Uncorrected error
Error enabled
MCi_MISC register valid
Processor context corrupt
MCA: Internal unclassified error: 405
STATUS fa00000000400405 MCGSTATUS 0
MCGCAP 1000c18 APICID 42 SOCKETID 1 
CPUID Vendor Intel Family 6 Model 47

**Comment by andikleen** [comment]
I believe it can happen when your system uses ACPI error reporting, and the underlying ACPI method reports ERST_STATUS_HARDWARE_NOT_AVAILABLE. As to why it does that I don't know. Should be harmless, that normal MCE reporting will still work as expected.
