### ISSUE TITLE
mcelog: ERROR: AMD Processor family 23: mcelog does not support this processor.  Please use the edac_mce_amd module instead.

### ISSUE THREAD

**Issue by commandline-be** [andikleen/mcelog#80]
lsmod | grep edac
edac_mce_amd           32768  0

systemctl status mcelog
● mcelog.service - Machine Check Exception Logging Daemon
   Loaded: loaded (/lib/systemd/system/mcelog.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2020-06-21 08:56:16 CEST; 28min ago
Condition: start condition failed at Sun 2020-06-21 09:24:22 CEST; 8s ago
           └─ ConditionPathExists=!/sys/module/edac_mce_amd/initstate was not met
 Main PID: 174091 (code=exited, status=1/FAILURE)

Jun 21 08:56:16 povx systemd[1]: Started Machine Check Exception Logging Daemon.
Jun 21 08:56:16 povx mcelog[174091]: mcelog: ERROR: AMD Processor family 23: mcelog does not support this processor.  Please use the edac_mce_amd module instead.
Jun 21 08:56:16 povx mcelog[174091]: CPU is unsupported
Jun 21 08:56:16 povx systemd[1]: mcelog.service: Main process exited, code=exited, status=1/FAILURE
Jun 21 08:56:16 povx systemd[1]: mcelog.service: Failed with result 'exit-code'.
Jun 21 08:56:36 povx systemd[1]: Condition check resulted in Machine Check Exception Logging Daemon being skipped.
Jun 21 09:24:15 povx systemd[1]: Condition check resulted in Machine Check Exception Logging Daemon being skipped.
Jun 21 09:24:22 povx systemd[1]: Condition check resulted in Machine Check Exception Logging Daemon being skipped.

**Comment by paulmenzel** [comment]
`edac_mce_amd` directly decodes the MCE messages in the Linux logs. For example from the [SUSE knowledge base](https://www.suse.com/support/kb/doc/?id=000018134):

> If a hardware error is found, edac_mce_amd does not log into /var/log/mcelog but into /var/log/messages instead.

**Comment by commandline-be** [comment]
> `edac_mce_amd` directly decodes the MCE messages in the Linux logs. For example from the [SUSE knowledge base](https://www.suse.com/support/kb/doc/?id=000018134):
> 
> > If a hardware error is found, edac_mce_amd does not log into /var/log/mcelog but into /var/log/messages instead.

Hi Paul. Not sure what you mean to say here. I do indeed get the 'Hardware Error' messages in /var/log/messages , i also get the notification 

Active: failed (Result: exit-code) since Sun 2020-06-21 08:56:16 CEST; 28min ago
Condition: start condition failed at Sun 2020-06-21 09:24:22 CEST; 8s ago
└─ ConditionPathExists=!/sys/module/edac_mce_amd/initstate was not met

**Comment by paulmenzel** [comment]
The `Hardware Error` messages are already the decoded MCEs. You do not need `mcelog`.

**Comment by commandline-be** [comment]
Ah, so i understood correctly. Thanks for pointing this out. 
Still impressed with what mcelog offers, does edac_mce_amd really cover everything mcelog offeres ?

**Comment by commandline-be** [comment]
Adequate response. Still curious if anything is missing from the logs compared to mcelog when depending on edac_mce_amd

**Comment by andikleen** [comment]
Yes some stuff is missing. mcelog has various functionality that is not in edac, e.g. triggers or more advanced offlining.

**Comment by commandline-be** [comment]
A bit sad really. I must have missed the big notification on the mcelog website explaining this :D
With this module available as source, could mcelog not integrate it in a way ? 
Sorry to ask dumb questions, i work on multiple topics rather far apart, i try to keep digging into docs to a minium.
