### ISSUE TITLE
/mce/tests/page  test failure

### ISSUE THREAD

**Issue by lumanyu180** [andikleen/mcelog#88]
hi, 
I test mcelog , but got the error, 
page-soft-then-hard.conf: triggers did not trigger as expected: 4 != 6 
My mcelog version is : mcelog mcelog-144-10.94d853b2ea81.el7 
I see it inject 6 error，and page-soft-then-hard.conf has memory-ce-threshold = 1 / 1h，so i think mcelog should run triggers 6 times. Why  page-soft-then-hard.conf has trigger: 4 ? 

Thanks very much!

**Comment by QiuxuZhuo** [comment]
@lumanyu180 ,
I think this issue #88 is same to #90: [https://github.com/andikleen/mcelog/issues/90]

**Comment by andikleen** [comment]
Closed as duplicate
