### ISSUE TITLE
Lockdown: mcelog: raw MSR access is restricted; see man kernel_lockdown.7

### ISSUE THREAD

**Issue by TheFeshy** [andikleen/mcelog#96]
This message is from the kernel, when booting in SecureBoot mode.  According to kernel_lockdown.7, this is the expected behavior when secure booting kernels 5.4 and later.  Raw access to MSR is denied for security issues.

Unfortunately, I have no idea what this means for mcelog - is some functionality unavailable?  Will it simply fail silently?  Some note in the documentation (or message printed by mcelog when it is denied access to the MSR) explaining the consequences would be very helpful.

I encountered this in Fedora 34, while booting into a signed EFI kernel image.

**Comment by andikleen** [comment]
When an memory error occurs mcelog won't be able to identify the DIMM. Other than that it's harmless.

Should probably have a better error message for this.
